version: '2'

services:
  taiga:
    build: .
    ports:
      - 80:80
    volumes:
      # Volume that maps to taiga's media,
      # this way uploaded files are not lost during upgrades of the taiga image
      - ./media:/usr/src/taiga-back/media

    environment:
      # Your hostname (REQUIRED)
      TAIGA_HOSTNAME: localhost

      # Database settings
      # To use an external database, simply update these and remove the postgres
      # service from this docker-compose.yml file
      TAIGA_DB_NAME: taiga
      TAIGA_DB_HOST: analytics-db-ca-1a
      TAIGA_DB_USER: taiga_user
      TAIGA_DB_PASSWORD: "TaigaPassword2019"
      TAIGA_SLEEP: 1 # when the db comes up from docker, it is usually too quick

      # To use an external SMTP for emails, fill in these values:
      # TAIGA_ENABLE_EMAIL: True
      # TAIGA_EMAIL_FROM: no-reply@taiga.mycompany.net
      # TAIGA_EMAIL_USE_TLS: True
      # TAIGA_EMAIL_HOST: smtp.google.com
      # TAIGA_EMAIL_PORT: 587
      # TAIGA_EMAIL_USER: me@gmail.com
      # TAIGA_EMAIL_PASS: super-secure-pass phrase thing!
